name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint (optional)
        run: |
          if command -v flake8 >/dev/null 2>&1; then flake8 || true; fi
      - name: Run tests
        run: |
          if [ -f pytest.ini ] || [ -d tests ]; then pytest -q || true; fi